In [3]:
import pandas as pd

df = pd.read_csv('/content/customer_support_tickets_200k.csv')

print(df.isnull().sum())

ticket_id                          0
customer_name                      0
customer_email                     0
product                            0
category                           0
issue_description                  0
resolution_notes                   0
priority                           0
status                             0
channel                            0
region                             0
customer_age                       0
customer_gender                    0
subscription_type                  0
customer_tenure_months             0
previous_tickets                   0
customer_satisfaction_score        0
first_response_time_hours          0
resolution_time_hours              0
ticket_created_date                0
ticket_resolved_date               0
escalated                          0
sla_breached                       0
operating_system                   0
browser                        40023
payment_method                     0
language                           0
preferred_contact_time             0
issue_complexity_score             0
customer_segment                   0
dtype: int64

In [4]:
df.drop(columns=['browser'], inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 29 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ticket_id                    200000 non-null  int64
 1   customer_name                200000 non-null  object
 2   customer_email               200000 non-null  object
 3   product                      200000 non-null  object
 4   category                     200000 non-null  object
 5   issue_description            200000 non-null  object
 6   resolution_notes             200000 non-null  object
 7   priority                     200000 non-null  object
 8   status                       200000 non-null  object
 9   channel                      200000 non-null  object
 10  region                       200000 non-null  object
 11  customer_age                 200000 non-null  int64
 12  customer_gender              200000 non-null  object
 13  subscription_type            200000 non-null  object
 14  customer_tenure_months       200000 non-null  int64
 15  previous_tickets             200000 non-null  int64
 16  customer_satisfaction_score  200000 non-null  int64
 17  first_response_time_hours    200000 non-null  float64
 18  resolution_time_hours        200000 non-null  float64
 19  ticket_created_date          200000 non-null  object
 20  ticket_resolved_date         200000 non-null  object
 21  escalated                    200000 non-null  object
 22  sla_breached                 200000 non-null  object
 23  operating_system             200000 non-null  object
 24  payment_method               200000 non-null  object
 25  language                     200000 non-null  object
 26  preferred_contact_time       200000 non-null  object
 27  issue_complexity_score       200000 non-null  int64
 28  customer_segment             200000 non-null  object
dtypes: float64(2), int64(6), object(21)
memory usage: 44.3+ MB

In [6]:
df.head()

,ticket_id,customer_name,customer_email,product,category,issue_description,resolution_notes,priority,status,channel,...,ticket_created_date,ticket_resolved_date,escalated,sla_breached,operating_system,payment_method,language,preferred_contact_time,issue_complexity_score,customer_segment
0,1,Patricia Smith,patricia.smith760@outlook.com,Web Portal,Account Suspension,The payment was deducted from my bank account ...,Data synchronization restored after backend se...,Urgent,Open,Email,...,2023-05-17,2023-05-20,No,Yes,MacOS,PayPal,French,Afternoon,4,Small Business
1,2,Patricia Williams,patricia.williams390@gmail.com,Mobile App,Performance Issue,I found a bug in the latest update affecting r...,Provided step-by-step troubleshooting instruct...,Urgent,Closed,Email,...,2024-01-06,2024-01-19,Yes,Yes,Windows,PayPal,English,Afternoon,2,Small Business
2,3,William Anderson,william.anderson651@outlook.com,Web Portal,Performance Issue,The application crashes whenever I try to uplo...,Provided step-by-step troubleshooting instruct...,Medium,Closed,Chat,...,2022-11-30,2022-12-05,Yes,Yes,Windows,Bank Transfer,French,Morning,4,Corporate
3,4,David Miller,david.miller672@icloud.com,Payment Gateway,Subscription Cancellation,My subscription was cancelled without my reque...,Provided step-by-step troubleshooting instruct...,Medium,Closed,Social Media,...,2024-03-21,2024-04-04,Yes,No,Windows,Credit Card,Spanish,Afternoon,7,Corporate
4,5,Robert Gonzalez,robert.gonzalez391@hotmail.com,Web Portal,Feature Request,The system is not syncing data across devices ...,We have reset the account credentials and advi...,High,Pending Customer,Email,...,2024-08-16,2024-08-24,Yes,No,Linux,Debit Card,Spanish,Evening,3,Corporate

In [8]:
print(df.duplicated(subset=['ticket_id']).sum())

0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 29 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ticket_id                    200000 non-null  int64
 1   customer_name                200000 non-null  object
 2   customer_email               200000 non-null  object
 3   product                      200000 non-null  object
 4   category                     200000 non-null  object
 5   issue_description            200000 non-null  object
 6   resolution_notes             200000 non-null  object
 7   priority                     200000 non-null  object
 8   status                       200000 non-null  object
 9   channel                      200000 non-null  object
 10  region                       200000 non-null  object
 11  customer_age                 200000 non-null  int64
 12  customer_gender              200000 non-null  object
 13  subscription_type            200000 non-null  object
 14  customer_tenure_months       200000 non-null  int64
 15  previous_tickets             200000 non-null  int64
 16  customer_satisfaction_score  200000 non-null  int64
 17  first_response_time_hours    200000 non-null  float64
 18  resolution_time_hours        200000 non-null  float64
 19  ticket_created_date          200000 non-null  object
 20  ticket_resolved_date         200000 non-null  object
 21  escalated                    200000 non-null  object
 22  sla_breached                 200000 non-null  object
 23  operating_system             200000 non-null  object
 24  payment_method               200000 non-null  object
 25  language                     200000 non-null  object
 26  preferred_contact_time       200000 non-null  object
 27  issue_complexity_score       200000 non-null  int64
 28  customer_segment             200000 non-null  object
dtypes: float64(2), int64(6), object(21)
memory usage: 44.3+ MB

In [10]:
df['ticket_created_date'] = pd.to_datetime(df['ticket_created_date'])
df['ticket_resolved_date'] = pd.to_datetime(df['ticket_resolved_date'])

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 29 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ticket_id                    200000 non-null  int64
 1   customer_name                200000 non-null  object
 2   customer_email               200000 non-null  object
 3   product                      200000 non-null  object
 4   category                     200000 non-null  object
 5   issue_description            200000 non-null  object
 6   resolution_notes             200000 non-null  object
 7   priority                     200000 non-null  object
 8   status                       200000 non-null  object
 9   channel                      200000 non-null  object
 10  region                       200000 non-null  object
 11  customer_age                 200000 non-null  int64
 12  customer_gender              200000 non-null  object
 13  subscription_type            200000 non-null  object
 14  customer_tenure_months       200000 non-null  int64
 15  previous_tickets             200000 non-null  int64
 16  customer_satisfaction_score  200000 non-null  int64
 17  first_response_time_hours    200000 non-null  float64
 18  resolution_time_hours        200000 non-null  float64
 19  ticket_created_date          200000 non-null  datetime64[ns]
 20  ticket_resolved_date         200000 non-null  datetime64[ns]
 21  escalated                    200000 non-null  object
 22  sla_breached                 200000 non-null  object
 23  operating_system             200000 non-null  object
 24  payment_method               200000 non-null  object
 25  language                     200000 non-null  object
 26  preferred_contact_time       200000 non-null  object
 27  issue_complexity_score       200000 non-null  int64
 28  customer_segment             200000 non-null  object
dtypes: datetime64[ns](2), float64(2), int64(6), object(19)
memory usage: 44.3+ MB

In [12]:
df.head()

,ticket_id,customer_name,customer_email,product,category,issue_description,resolution_notes,priority,status,channel,...,ticket_created_date,ticket_resolved_date,escalated,sla_breached,operating_system,payment_method,language,preferred_contact_time,issue_complexity_score,customer_segment
0,1,Patricia Smith,patricia.smith760@outlook.com,Web Portal,Account Suspension,The payment was deducted from my bank account ...,Data synchronization restored after backend se...,Urgent,Open,Email,...,2023-05-17,2023-05-20,No,Yes,MacOS,PayPal,French,Afternoon,4,Small Business
1,2,Patricia Williams,patricia.williams390@gmail.com,Mobile App,Performance Issue,I found a bug in the latest update affecting r...,Provided step-by-step troubleshooting instruct...,Urgent,Closed,Email,...,2024-01-06,2024-01-19,Yes,Yes,Windows,PayPal,English,Afternoon,2,Small Business
2,3,William Anderson,william.anderson651@outlook.com,Web Portal,Performance Issue,The application crashes whenever I try to uplo...,Provided step-by-step troubleshooting instruct...,Medium,Closed,Chat,...,2022-11-30,2022-12-05,Yes,Yes,Windows,Bank Transfer,French,Morning,4,Corporate
3,4,David Miller,david.miller672@icloud.com,Payment Gateway,Subscription Cancellation,My subscription was cancelled without my reque...,Provided step-by-step troubleshooting instruct...,Medium,Closed,Social Media,...,2024-03-21,2024-04-04,Yes,No,Windows,Credit Card,Spanish,Afternoon,7,Corporate
4,5,Robert Gonzalez,robert.gonzalez391@hotmail.com,Web Portal,Feature Request,The system is not syncing data across devices ...,We have reset the account credentials and advi...,High,Pending Customer,Email,...,2024-08-16,2024-08-24,Yes,No,Linux,Debit Card,Spanish,Evening,3,Corporate

In [13]:
df.to_csv('cleaned_support_tickets.csv', index=False)